Update goodsong

diff --git a/utils/goodsong b/utils/goodsong
--- a/utils/goodsong
+++ b/utils/goodsong
@@ -9,35 +9,51 @@ COLX="\e[0m"
 
 WORKFILE=$HOME/.config/goodsongs
 LASTFILE=$WORKFILE.last
-SONGURL=$(sort -R $WORKFILE | head -n 1)
-LASTURL=$(cat $LASTFILE)
-TITLE=$(links -source $SONGURL | grep "eow-title" | gawk -F \" '{print $8}')
-NOWPLAYING="$PURPLE$TITLE$COLX —— $CYAN$SONGURL"
+
+LINE=$(sort -R $WORKFILE | head -n 1)
+
+NUMSONGS="$GREEN$(wc -l $WORKFILE | tr -d " $WORKFILE")$COLX"
+SONGURL=$(echo $LINE | cut -d ';' -f1)
+ARTIST=$(echo $LINE | cut -d ';' -f2)
+TITLE=$(echo $LINE | cut -d ';' -f3)
+
+LASTURL=$(cat $LASTFILE | cut -d ';' -f1)
+
+NOWPLAYING="$PURPLE$ARTIST - $TITLE$COLX —— $CYAN$SONGURL"
 TITLE=$(echo $TITLE | tr -d ' ')
 PLAYER=audacious
-NUMSONGS="$GREEN$(wc -l $WORKFILE | tr -d " $WORKFILE")$COLX"
 
-if   [ "$1" == "add" ]; then
-    if [ -n "$2" ] && ! [ -n "$(grep -w $2 $WORKFILE)" ]; then
-        echo "$2" >> $WORKFILE
-        echo "$2" > $LASTFILE
-        exit 0
-    else
-        echo -e "$RED[FAIL]$COLX $PURPLEPut a URL that's not there, dummy!"
-        exit 1
-    fi
-elif [ "$1" == "undo" ]; then
-    grep -v "$LASTURL" $WORKFILE > $WORKFILE.temp && mv $WORKFILE.temp $WORKFILE
+while getopts "dUnt:a:u:" flag; do
+	case "${flag}" in
+		n) new=1 ;;
+		t) newtitle="${OPTARG}" ;;
+		a) newartist="${OPTARG}" ;;
+		u) newurl="${OPTARG}" ;;
+		U) undo=1 ;;
+		d) dl=1 ;;
+	esac
+done
+
+if [ -n "$new" ] && [ -z $(grep -w "$newartist" $WORKFILE | grep "$newtitle") ] 2>> /dev/null; then
+    echo "$newurl;$newartist;$newtitle" >> $WORKFILE 
+    echo "$newurl;$newartist;$newtitle" > $LASTFILE
     exit 0
-elif [ "$1" == "dl" ]; then
+elif [ "$undo" == "1" ]; then
+    sed -v "/$LASTURL/d" $WORKFILE > $WORKFILE.temp && mv $WORKFILE.temp $WORKFILE
+    exit 0
+elif [ "$dl" == "1" ]; then
     youtube-dl -f 140 -o /tmp/$TITLE $SONGURL
     echo "$SONGURL" > $LASTFILE
-    echo "Playing $TITLE"
+    echo "$RED[GOODSONG]$COLX Now playing: $NOWPLAYING"
     screen -m -d $PLAYER /tmp/$TITLE
     exit 0
+elif [ -n "$new" ]; then
+    echo -e "$RED[FAIL]$COLX Put a song that's not there, dummy!"
+    exit 1
+else
+    echo -e "$RED[GOODSONG]$COLX There are $NUMSONGS songs to shuffle from!"
+    echo -e "$RED[GOODSONG]$COLX Now playing: $NOWPLAYING"
+    x-www-browser $SONGURL 2>> /dev/null
+    echo "$SONGURL" > $LASTFILE
+    exit 0
 fi
-
-echo -e "$RED[GOODSONG]$COLX There are $NUMSONGS songs to shuffle from!"
-echo -e "$RED[GOODSONG]$COLX Now playing: $NOWPLAYING"
-x-www-browser $SONGURL 2>> /dev/null
-echo "$SONGURL" > $LASTFILE
